apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-mysql
  namespace: database
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: container-mysql
        image: 964581984848.dkr.ecr.us-east-1.amazonaws.com/my_sql:v0.1
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw