---
apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod
  namespace: application
  labels:
    app: employees
spec:
  containers:
    - name: web-app
      image: 964581984848.dkr.ecr.us-east-1.amazonaws.com/web_app:v0.1
      ports:
        - containerPort: 8080
      env:
        - name: DBHOST
          value: "svc-mysql.database.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "pw"
        - name: DATABASE
          value: "employees"
        - name: APP_COLOR
          value: "blue"