---
apiVersion: v1
kind: Pod
metadata:
  name: pod-mysql
  namespace: database
  labels:
    app: mysql
spec:
  containers:
    - name: mysql-app
      image: 964581984848.dkr.ecr.us-east-1.amazonaws.com/my_sql:v0.1
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw