---
apiVersion: v1
kind: Service
metadata:
  name: svc-webapp
  namespace: application
spec:
  selector:
    app: employees
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort